### Insert User
POST http://localhost:9000/user
Content-Type: application/json

{
  "username": "example_user3",
  "email": "example3@email.com",
  "password": "secure_password",
  "firstName": "Yuri",
  "lastName": "User",
  "isPasswordHashed": false
}

### Find user by username
GET http://localhost:9000/user/username/example_user3