### insert EmotionRecord
POST http://localhost:9000/emotionRecord
Content-Type: application/json

{
  "emotionRecord": {
    "id": 1,
    "userId": "1",
    "emotionId": "Joy",
    "intensity": 5,
    "created": "2023-04-01T13:04:47.271"
  },
  "subEmotions": [
    {
      "id": "Amusement",
      "subEmotionName": "Amusement",
      "emotionId": "Joy",
      "created": "2023-04-01T13:04:47.272"
    }
  ],
  "triggers": [
    {
      "id": 1,
      "triggerName": "Person",
      "parentId": 1,
      "userId": 1,
      "description": "Listening to music",
      "created": "2023-04-01T13:04:47.273"
    }
  ]
}

###

# curl --location 'http://localhost:9000/emotionRecord'
# Get all EmotionRecords
GET http://localhost:9000/emotionRecord

###





