### Insert EmotionRecord
POST http://localhost:9000/api/emotionRecord
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MTI3NzY5MzksImlhdCI6MTY4MTI0MDkzOSwidXNlcklkIjozLCJ1c2VybmFtZSI6IkZpZnR5b25lQWRtaW5Vc2VyMSIsImVtYWlsIjoiRmlmdHlvbmVBZG1pblVzZXIxQGVtYWlsLmNvbSIsImZpcnN0bmFtZSI6Ill1cmkiLCJsYXN0bmFtZSI6IlVzZXIiLCJyb2xlIjoidXNlciJ9.brtjzMVjEv_h_MiZkCjuexDovZFBkm-eYlQdSAXR1n4

{
  "userId": 3,
  "emotionId": "Joy",
  "intensity": 7,
  "subEmotions": [
    {
      "subEmotionId": "Amusement"
    },
    {
      "subEmotionId": "Charm"
    }
  ],
  "triggers": [
    {
      "triggerId": 1
    }
  ]
}