services:
  rig:
    image: ghcr.io/rigdev/rig:1.1.2
    environment:
      RIG_AUTH_JWT_SECRET: mysecret
      RIG_CLIENT_MONGO_HOST: mongo:27017
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "4747:4747"

  mongo:
    image: "mongo:latest"
    volumes:
      - mongo-data:/data'

volumes:
  mongo-data:

networks:
  default:
    name: rig