version: "3"
services:
  db:
    image: mysql:5.7
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
  app:
    image: projectemo:1.0.2-SNAPSHOT
    ports:
      - "9000:9000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./logs:/opt/projectemo/logs